version: '3.2'
services: 
  backend:
    build: ./app

  nginx:
    build: ./web-server
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/letsencrypt
      - certs_data:/data/letsencrypt

  # letsencrypt:
  #   image: deliverous/certbot
  #   volumes:
  #     - certs:/etc/letsencrypt
  #     - certs_data:/data/letsencrypt
  #   command: "certonly --webroot --webroot-path=/data/letsencrypt --renew-by-default -d babydrop.zone --email mattcarpowich@gmail.com --agree-tos --no-eff-email --non-interactive"

volumes:
  backend:
  certs:
  certs_data: